### ISSUE TITLE
the warning of No GPUs detected in the job of cryodrgn train_vae

### ISSUE THREAD

**Issue by bingwang14** [ml-struct-bio/cryodrgn#212]
Dear all,

Does anyone know how to fix the warning of No GPUs detected in train_vae job? Here is the full warning below.
////
/home/xx/.conda/envs/crDGN/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py:118: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
/home/xx/.conda/envs/crDGN/lib/python3.9/site-packages/torch/amp/autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
////

Our workstation is equipped with 4 GeForce RTX 2080ti with cuda driver 11.0 (450.216.04). I actually tried cuda toolkit in anaconda env cryodrgn from 10.0 to 11.0. but the problem of "CUDA not available" and "No GPUs detected" is always there. BTW, the pytorch version is 1.13.1.

Thank you in advance!
Bing

**Comment by bingwang14** [comment]
This issue has been solved by reinstalling pytorch of version 1.12

**Comment by ic1062** [comment]
Hello, I am having trouble resolving the "no GPUs detected" problem. Will you please provide details about how to install with pytorch version 1.12?

Michael

**Comment by ic1062** [comment]
I solved this using the method provided by @jelka71  (https://github.com/zhonge/cryodrgn/issues/271)

conda create --name cdrgn2.3 python=3.9
conda activate cdrgn2.3
conda install pytorch-gpu cudatoolkit=11.4 -c conda-forge
git clone https://github.com/zhonge/cryodrgn.git
cd cryodrgn
pip install .
